[tool.poetry]
name = "auth"
version = "0.0.1"
authors = ["PauLark inc."]
description = "Another one auth service"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.3"
uvicorn = "^0.29.0"
pydantic-settings = "^2.2.1"
dynaconf = "^3.2.5"
motor = "^3.4.0"