[default]
debug = true
service_name = "auth"
allow_origins = ["*"]
password_min_length = 9
signing_algorithm = "HS256"
access_token_exp_minutes = 500000
refresh_token_exp_minutes = 6000000

[default.mongo]
url = "mongodb://localhost:27017"
database_name = "test"